apiVersion: v1
kind: Pod
metadata:
  name: aplicacao
  labels:
    name: aplicacao
spec:
  containers:
  - name: container-aplicacao-loja
    image: rafanercessian/aplicacao-loja:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80